use strict;
use vars qw($lang);
use CGI::LZE qw(:lze param $params);
init("t/settings.pl");
*lang = \$CGI::LZE::lng;
use Test::More tests => 5;
$ENV{HTTP_ACCEPT_LANGUAGE} = "de";
ok(translate('firstname') eq 'Vorname');
$ENV{HTTP_ACCEPT_LANGUAGE} = "en";
ok(translate('username')  eq 'User');
ok($lang->{de}{firstname} eq 'Vorname');
ok($lang->{en}{username}  eq 'User');
init("t/settings.pl");
my %vars = (user => 'guest', action => 'main', file => "t/content.pl", sub => 'main');
my $qstring = createSession(\%vars);
param(-name => 'include', -value => $qstring);
include($qstring);
ok($params->{test} eq "OK");
clearSession();
